name: CI/CD Pipeline

# for ANY push, this workflow will be triggered
on: [push]

jobs:
  build:
    # ubuntu provides environment for running builds/tests
    runs-on: ubuntu-latest

    steps:
    # checkpout "clones" the repo code to here
    - uses: actions/checkout@v2

    # set up Python env.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest

    - name: Run tests
      run: |
          pytest tests/
      # pytest test_app.py
      
    
    - name: Deploy to Heroku
      env: 
        # Use the Heroku API key from GitHub secrets
        HEROKU_API_KEY: ${{ secretes.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://git.heroku.com/your-app-name.git  # Add Heroku remote repository
        git push heroku master                                          # Push code to Heroku for deployment

        


