name: CI/CD Pipeline

# for ANY push, this workflow will be triggered
on: [push]

jobs:
  build:
    # ubuntu provides environment for running builds/tests
    runs-on: ubuntu-latest

    steps:
    # checkpout "clones" the repo code to here
    - uses: actions/checkout@v2

    # set up Python env.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest

    - name: Run tests
      run: |
          pytest tests/
      # pytest test_app.py
      
    
    - name: Deploy to PythonAnywhere
      env: 
        # Use the PythonAnywhere API key from GitHub secrets
        PYTHONANYWHERE_API_KEY: ${{ secrets.PYTHONANYWHERE_API_KEY }}
      run: |
        pa_autoconfigure_flask.py --python=3.8 https://github.com/sahildadhwal/ItineraryPlanner.git

      
